spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-devit-board.copkmnpqtze8.ap-northeast-2.rds.amazonaws.com:3306/devit_board?serverTimezone=Asia/Seoul
    username: jeeho
    password: 12345678
  rabbitmq:
    host: 52.79.236.81
    password: 1234
    port: 5672
    username: devit
    exchange: x.devit.board
    queue: q.devit.board
    routingkey: devit.routingkey
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: board-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize : 12MB
  logging:
    level:
      root: info
    file:
      name: /home/ubuntu/log/application-debug.log
cloud:
  aws:
    credentials:
      accessKey: AKIA5OW66KNY5ENMSAYI
      secretKey: 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
    s3:
      bucket: devit-board
    region:
      static: ap-northeast-2
    stack:
      auto: false 


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
